### ISSUE TITLE
400 ProtocolError with Streaming API

### ISSUE THREAD

**Issue by cyu** [timdorr/tesla-api#191]
We've started having issues with the Streaming API and it appears that there is an issue with the async-websocket gem.

The stream method currently will hang under the latest released version of async-websocket (0.14.0). I submitted a patch to fix the hang (https://github.com/socketry/async-websocket/pull/24), but instead raises a ProtocolError with a status code of 400.  Figuring out why it's throwing a 400 error is beyond my current understanding of the websocket protocol - it appears the issue is happening during handshake, when upgrading the connection to a websocket connection.

I then tested the streaming functionality with the carson python library to verify that there hasn't been any significant changes to the streaming API. It works fine there.

Finally, to get around this issue I reimplemented the streaming API using another ruby [websocket library](https://github.com/imanel/websocket-eventmachine-client) gem.

**Comment by timdorr** [comment]
Does the prior Faye version of this have the same issue? https://github.com/timdorr/tesla-api/blob/36ac62bdec45fcf6fbbb03f11d86000994ea3e3d/lib/tesla_api/stream.rb

**Comment by ioquatix** [comment]
We released the update you proposed in v0.15.0 - can you elaborate or give a test case to reproduce the failure?

**Comment by cyu** [comment]
@timdorr I just tested against v3.0.2 of the gem, which seems to be the last version that uses Faye) and the streaming works there.  Unfortunately, that EventMachine implementation is tricky to work with since it blocks that thread until EM is stopped, which unfortunately stops *all* EM jobs.

@ioquatix here's the test code. Unfortunately, unless you have access to a Tesla you won't be able to set the secrets to make this work:

```ruby
require "tesla_api"

email = "xxx"
access_token = "xxx"
access_token_expires_at = Time.at 1592710906
refresh_token = "xxx"
client_id = "xxx"
client_secret = "xxx"
vehicle_id = "xxx"

api = TeslaApi::Client.new(
  email: email,
  access_token: access_token,
  access_token_expires_at: access_token_expires_at,
  refresh_token: refresh_token,
  client_id: client_id,
  client_secret: client_secret
)
api.vehicle(vehicle_id).stream do |data|
  puts data
end
```

Output:
```
root@70b74686f715:/myapp# ruby ./tesla_stream_test.rb
 3.27s    error: Async::Task [oid=0x2ace11d683b4] [pid=93] [2020-05-24 15:30:14 +0000]
               |   Async::WebSocket::ProtocolError: Failed to negotiate connection: 400
               |   → /usr/local/bundle/gems/async-websocket-0.15.0/lib/async/websocket/client.rb:99 in `connect'
               |     /usr/local/bundle/gems/async-websocket-0.15.0/lib/async/websocket/client.rb:53 in `block in connect'
               |     /usr/local/bundle/gems/async-websocket-0.15.0/lib/async/websocket/client.rb:44 in `open'
               |     /usr/local/bundle/gems/async-websocket-0.15.0/lib/async/websocket/client.rb:52 in `connect'
               |     /usr/local/bundle/gems/tesla_api-3.0.4/lib/tesla_api/stream.rb:5 in `block in stream'
               |     /usr/local/bundle/gems/async-1.26.1/lib/async/task.rb:258 in `block in make_fiber'
```

If I switch the tesla_api version to 3.0.2, which uses Faye instead of Async, the same example above works.

**Comment by ioquatix** [comment]
Are you willing to share a token with me so I can test it?

**Comment by ioquatix** [comment]
It might be the case that the telsa API is HTTP/2 but only supports HTTP/1 websockets:

Can you try with the following:

```
endpoint = Async::HTTP::Endpoint.parse("https://remote-server.com", alpn_protocols: Async::HTTP::Protocol::HTTP11.names)

Async::WebSocket::Client.connect(endpoint) do ...
```

**Comment by timdorr** [comment]
Hmm, I tried to look into this but it appears Tesla is having some sort of technical glitch and I can't log in (API or the website). App still works, so I guess I still have an account. But it's a holiday, so I don't expect to be able to fix this until later in the week.

As soon as I can log in, I'll take a look!

**Comment by cyu** [comment]
@ioquatix I did a test with the `alpn_protocols` option, but it produced the same result.

These tokens aren't mine, so I can't really hand them over.

**Comment by ioquatix** [comment]
Are there any test tokens or any way to make test tokens?

**Comment by timdorr** [comment]
Nope, we're all external users of Tesla's API, so we can only use production data.

**Comment by ioquatix** [comment]
Anyone up for some peer coding then?

**Comment by cyu** [comment]
@ioquatix Apologies - I recently retested this your suggestion `alpn_protocols` suggestion and it does work.

I've created a PR for this fix: #219 

Thank you for your help!

**Comment by ioquatix** [comment]
Awesome, great work everyone. Now your Tesla is truly asynchronous.
